#!/bin/sh

umask 077

PGP=`which gpg`
FILE=~/Dropbox/pass/passwords.gpg
OUT=/tmp/pass.lock

${PGP} --decrypt -q -o ${OUT} ${FILE}

vim ${OUT}

${PGP} -e -r AE5705CE --yes -o ${FILE} ${OUT}

ls -l ${FILE}
rm -i ${OUT}
	
