#!/bin/sh

umask 077

help() {
    echo "Usage: $0 <recipient>"
    echo "  recipient    key ID or user name (e.g. 'lev')"
    exit 1
}

[ -z "$1" ] && help

PGP=`which gpg`
FILE=~/Dropbox/pass/passwords.gpg
OUT=`mktemp /tmp/passXXXXX`
RECIPIENT=$1

${PGP} --decrypt -q --yes -o ${OUT} ${FILE}

vim ${OUT}

${PGP} -e -r $RECIPIENT --yes -o ${FILE} ${OUT}

ls -l ${FILE}
rm -f ${OUT}
